export interface BlogArticle {
  slug: string
  title: string
  description: string
  category: string
  readTime: string
  date: string
  author: string
  authorRole: string
  coverGradient: string
  content: string[]
}

export const BLOG_CATEGORIES = [
  "All",
  "Context Engineering",
  "Prompt Engineering",
  "AI Tooling",
  "AI Agents",
  "AI Architecture",
] as const

export const blogArticles: BlogArticle[] = [
  {
    slug: "context-engineering-guide",
    title: "The Complete Guide to Context Engineering",
    description:
      "Context engineering is the discipline of designing and structuring the information you feed to an AI model. Learn the principles, patterns, and techniques that separate amateurs from experts.",
    category: "Context Engineering",
    readTime: "12 min read",
    date: "Apr 7, 2026",
    author: "Skyler Team",
    authorRole: "AI Research",
    coverGradient: "from-violet-600 to-indigo-600",
    content: [
      "## What Is Context Engineering?",
      "Context engineering is the practice of carefully curating and structuring the information that an AI model receives as input. Unlike prompt engineering, which focuses on how you phrase a question, context engineering is about *what information* you provide and *how it's organized*.",
      "Think of it this way: if a prompt is the question you ask, the context is the textbook you hand someone before asking that question. The quality of the answer depends heavily on the quality and relevance of that textbook.",
      "## Why Context Matters More Than Prompts",
      "A common misconception is that crafting the perfect prompt is the key to getting great AI outputs. In reality, the context surrounding your prompt is far more impactful. Here's why:",
      "**Token efficiency**: Modern LLMs have limited context windows. Every irrelevant token you include pushes out potentially useful information. Context engineering helps you maximize the signal-to-noise ratio.",
      "**Grounding**: Without proper context, AI models rely on their training data, which may be outdated or generic. Context engineering grounds the model in your specific domain, codebase, and requirements.",
      "**Consistency**: Well-structured context produces more consistent outputs. When the AI has a clear picture of your project's architecture, coding conventions, and constraints, it generates code that fits naturally.",
      "## The Four Pillars of Context Engineering",
      "### 1. Relevance Filtering",
      "Not all information is equally useful. The first pillar is learning to identify and include only the information that's directly relevant to the task at hand. This means understanding your AI model's strengths and knowing which details help versus which details create noise.",
      "### 2. Structural Organization",
      "How you order and format context dramatically affects output quality. We recommend a hierarchical approach: start with high-level architecture, then narrow down to the specific component, then to the exact function or feature you're working on.",
      "### 3. Explicit Constraints",
      "AI models perform best when given clear boundaries. List your tech stack, specify coding conventions, define error handling patterns, and state anti-patterns to avoid. Constraints reduce hallucinations and keep outputs focused.",
      "### 4. Example-Driven Reinforcement",
      "Including relevant code examples from your own codebase is one of the most powerful context techniques. When the AI sees how your team writes code, it adapts its style to match — producing more cohesive, maintainable output.",
      "## Practical Context Engineering Workflow",
      "Here's a step-by-step workflow for building effective context:",
      "**Step 1**: Define the objective. What exactly should the AI build or modify?\n**Step 2**: Gather architectural context — database schemas, API contracts, component hierarchies.\n**Step 3**: Include boundary files — the files the generated code will interact with.\n**Step 4**: State constraints — performance requirements, security considerations, style guides.\n**Step 5**: Provide examples — show 1–2 similar implementations from your codebase.",
      "## Common Anti-Patterns",
      "- **Context dumping**: Pasting an entire codebase into the prompt. This overwhelms the model and wastes tokens.\n- **Missing dependencies**: Asking the AI to modify a function without showing the types it depends on.\n- **Implicit assumptions**: Expecting the AI to know your team's unwritten conventions.\n- **Static context**: Using the same context template for every task instead of tailoring it.",
      "## The Future of Context Engineering",
      "As context windows grow larger (from 8K to 128K to 1M+ tokens), the principles of context engineering become even more important — not less. More space doesn't mean you should fill it all. It means you have room to provide *better* context, not *more* context.",
      "Tools like Skyler automate the most tedious parts of context engineering by analyzing your project structure, extracting relevant files, and generating optimized prompts that give AI editors exactly the context they need.",
    ],
  },
  {
    slug: "prompt-engineering-101",
    title: "Prompt Engineering 101: From Basics to Mastery",
    description:
      "Master the art and science of prompt engineering. From zero-shot to chain-of-thought, learn the techniques that professionals use to get consistently great results from AI models.",
    category: "Prompt Engineering",
    readTime: "10 min read",
    date: "Apr 5, 2026",
    author: "Skyler Team",
    authorRole: "Developer Advocacy",
    coverGradient: "from-blue-600 to-cyan-500",
    content: [
      "## What Is Prompt Engineering?",
      "Prompt engineering is the practice of designing and refining the instructions you give to AI models to achieve specific, high-quality outputs. It's part art, part science — combining linguistic precision with an understanding of how language models process information.",
      "## The Spectrum of Prompting Techniques",
      "### Zero-Shot Prompting",
      "The simplest form. You give the AI a task with no examples. This works well for straightforward tasks where the model has strong training data. Example: *\"Write a Python function that sorts a list of dictionaries by a given key.\"*",
      "### Few-Shot Prompting",
      "Provide 2-5 examples of the desired input-output pattern before asking for the actual task. This dramatically improves consistency and quality, especially for tasks with specific formatting requirements.",
      "### Chain-of-Thought (CoT)",
      "Ask the model to think step by step. This technique is transformative for complex reasoning tasks — debugging, architecture decisions, algorithm design. By forcing the model to show its work, you get more accurate final answers.",
      "### Role-Based Prompting",
      "Assign the AI a specific role or persona: *\"You are a senior backend engineer specializing in distributed systems.\"* This activates domain-specific knowledge patterns and produces more expert-level outputs.",
      "## The Anatomy of a Great Prompt",
      "Every excellent prompt contains five elements:",
      "**1. Role**: Who the AI should be.\n**2. Context**: Background information and constraints.\n**3. Task**: The specific thing you want done.\n**4. Format**: How the output should be structured.\n**5. Examples**: What good output looks like.",
      "## Common Mistakes",
      "- Being too vague: *\"Make this better\"* vs *\"Refactor this function to use early returns and reduce nesting to max 2 levels.\"*\n- Overloading a single prompt with multiple unrelated tasks.\n- Not specifying the output format — then being frustrated when the result doesn't match your expectations.\n- Ignoring temperature and model selection for different use cases.",
      "## Advanced Techniques",
      "**Iterative Refinement**: Start broad, then narrow down. Use follow-up prompts to refine the output incrementally rather than trying to get perfection in one shot.",
      "**Negative Prompting**: Tell the model what NOT to do. *\"Do not use any deprecated APIs. Do not include inline styles.\"* Negative constraints are surprisingly effective.",
      "**Meta-Prompting**: Ask the AI to help you write better prompts. *\"What additional context would you need to generate a production-ready implementation of this feature?\"*",
      "## When to Use Prompt Engineering vs Context Engineering",
      "Prompt engineering and context engineering are complementary. Use prompt engineering when you need to control *how* the AI approaches a task. Use context engineering when you need to control *what information* the AI works with. In practice, every great AI interaction uses both.",
    ],
  },
  {
    slug: "how-ai-code-editors-work",
    title: "How AI Code Editors Actually Work",
    description:
      "A deep-dive into the architecture behind tools like Cursor, Windsurf, and Copilot. Understand the retrieval pipelines, context assembly, and generation loops that power modern AI coding assistants.",
    category: "AI Tooling",
    readTime: "14 min read",
    date: "Apr 3, 2026",
    author: "Skyler Team",
    authorRole: "Engineering",
    coverGradient: "from-emerald-600 to-teal-500",
    content: [
      "## The Rise of AI-Native Editors",
      "AI code editors have evolved from simple autocomplete tools to full-fledged pair programmers. Tools like Cursor, Windsurf, and GitHub Copilot can now understand entire codebases, generate multi-file changes, and even run and debug code autonomously.",
      "But how do they actually work under the hood?",
      "## The Core Architecture",
      "Every modern AI code editor follows a similar three-stage pipeline:",
      "### Stage 1: Context Retrieval",
      "When you ask an AI editor for help, the first thing it does is figure out what context to include. This typically involves:\n- **File graph analysis**: Understanding which files import from or depend on each other.\n- **Semantic search**: Using embeddings to find code snippets relevant to your query.\n- **Recency weighting**: Prioritizing recently edited files.\n- **Active file context**: Always including the file you're currently editing.",
      "### Stage 2: Prompt Assembly",
      "The retrieved context is assembled into a structured prompt. This is where the magic happens. The editor must decide:\n- Which files to include in full vs which to summarize.\n- How to order the context (most relevant first, or architectural context first?).\n- What system instructions to use (coding style, language preferences, framework conventions).\n- How to frame the user's request within the broader context.",
      "### Stage 3: Generation & Application",
      "The assembled prompt is sent to an LLM (typically GPT-4, Claude, or Gemini). The model generates code, which the editor then:\n- Parses and validates for syntax correctness.\n- Applies as a diff to the existing code.\n- Optionally runs linting and type-checking.\n- Presents to the user for review.",
      "## The Context Window Challenge",
      "The biggest technical challenge in AI editors is the context window. Modern codebases have thousands of files, but even the largest LLMs can only process a limited number of tokens at once. This means editors must be incredibly smart about what to include and what to leave out.",
      "## How Skyler Fits In",
      "Skyler sits at Stage 2 of this pipeline — prompt assembly. While AI editors do their own context retrieval, they don't always get it right. By using Skyler to generate optimized, pre-structured prompts with the right context, you can dramatically improve the quality of AI-generated code.",
      "Think of Skyler as a context pre-processor: it understands your project architecture, gathers the right files, applies your constraints, and outputs a prompt that any AI editor can use effectively.",
      "## What's Next for AI Editors",
      "The next generation of AI editors will feature:\n- **Multi-agent architectures**: Separate agents for planning, coding, testing, and reviewing.\n- **Persistent memory**: Remembering your preferences, past decisions, and project context across sessions.\n- **Tool use**: AI editors that can run terminal commands, interact with APIs, and use browser tools autonomously.\n- **Real-time collaboration**: Multiple AI agents working together on different parts of a codebase simultaneously.",
    ],
  },
  {
    slug: "architecture-prompts",
    title: "Architecture Prompts: Building Production-Grade Apps",
    description:
      "Learn how to write architectural prompts that guide AI code editors to generate well-structured, scalable, production-ready applications — not just throwaway prototypes.",
    category: "Prompt Engineering",
    readTime: "9 min read",
    date: "Apr 1, 2026",
    author: "Skyler Team",
    authorRole: "Product",
    coverGradient: "from-amber-500 to-orange-600",
    content: [
      "## Beyond \"Build Me a Todo App\"",
      "Most people use AI to generate simple scripts or one-off functions. But the real power of AI-assisted coding is in building complex, production-grade applications. The key? Architecture prompts.",
      "## What Is an Architecture Prompt?",
      "An architecture prompt is a comprehensive document that describes not just *what* you want to build, but *how* it should be structured. It includes:\n- **Project overview**: A clear description of the application's purpose and scope.\n- **Tech stack**: Specific frameworks, libraries, and tools to use.\n- **Database schema**: Table structures, relationships, and constraints.\n- **API design**: Endpoints, request/response formats, and auth flows.\n- **Component hierarchy**: How the frontend is organized.\n- **Business logic**: Core algorithms and workflows.\n- **Constraints**: Performance, security, accessibility requirements.",
      "## The Skyler Approach",
      "Skyler generates architecture prompts by walking you through a structured wizard. You describe your project in plain English, select your tech stack, and Skyler assembles a comprehensive prompt that covers every layer of the application.",
      "## Example: SaaS Analytics Platform",
      "Here's a condensed example of what a Skyler-generated architecture prompt looks like:",
      "```\n# Project: SaaS Analytics Platform\n\n## Tech Stack\n- Frontend: Next.js 14 (App Router), Tailwind CSS, Recharts\n- Backend: Next.js API Routes, Supabase (Postgres + Auth)\n- Deployment: Vercel\n\n## Database Schema\n- users: id, email, org_id, role, created_at\n- events: id, user_id, event_type, properties (jsonb), timestamp\n- dashboards: id, org_id, title, config (jsonb)\n\n## Authentication\n- Supabase Auth with email/password and Google OAuth\n- Row Level Security on all tables scoped to org_id\n\n## Key Features\n1. Real-time event tracking with WebSocket updates\n2. Custom dashboard builder with drag-and-drop widgets\n3. Funnel analysis with configurable steps\n```",
      "## Why Architecture Prompts Work",
      "Architecture prompts work because they solve the biggest problem with AI code generation: **lack of coherence**. When you generate code piece by piece, each piece might be good individually but they don't fit together. Architecture prompts ensure the AI has a holistic view of your entire system, producing code that's cohesive from day one.",
      "## Tips for Better Architecture Prompts",
      "- **Be specific about versions**: \"Next.js 14\" not \"Next.js\". \"Supabase v2\" not \"Supabase\".\n- **Include anti-patterns**: *\"Do NOT use the Pages Router. Do NOT use client-side fetching for initial data.\"*\n- **Define the folder structure**: Tell the AI exactly where files should go.\n- **Specify error handling**: Define how errors should be caught, logged, and presented to users.\n- **Include deployment context**: Mention your hosting platform — it affects code patterns significantly.",
    ],
  },
  {
    slug: "context-windows-explained",
    title: "Context Windows Explained: Why Token Limits Matter",
    description:
      "Understand how context windows work in LLMs, why they matter for code generation, and how to maximize the value of every token you send to the model.",
    category: "Context Engineering",
    readTime: "8 min read",
    date: "Mar 28, 2026",
    author: "Skyler Team",
    authorRole: "AI Research",
    coverGradient: "from-pink-500 to-rose-600",
    content: [
      "## What Is a Context Window?",
      "A context window is the maximum amount of text (measured in tokens) that a language model can process at once. Think of it as the model's working memory. Everything the model sees — your prompt, the context you provide, and the output it generates — must fit within this window.",
      "## How Big Are Context Windows?",
      "Context windows have grown exponentially:\n- **GPT-3 (2020)**: 4,096 tokens (~3,000 words)\n- **GPT-4 (2023)**: 8K–128K tokens\n- **Claude 3 (2024)**: 200K tokens\n- **Gemini 2.0 (2025)**: 1M+ tokens",
      "A token is roughly ¾ of a word. Code is typically less token-efficient than prose because of syntax characters, indentation, and naming conventions.",
      "## Why Token Limits Matter for Coding",
      "When building with AI code editors, context windows create real constraints:\n- A mid-size Next.js project might have 50–100 files, easily exceeding 200K tokens if included raw.\n- Including too many files wastes tokens on irrelevant context.\n- Including too few files means the model misses important dependencies.",
      "## The Cost of Context",
      "Larger context windows aren't free. They come with:\n- **Higher latency**: More tokens = more processing time.\n- **Higher cost**: API pricing is per-token.\n- **Attention dilution**: Research shows that models struggle to attend equally to all parts of very long contexts. Information in the middle of a long context is often overlooked (the \"lost in the middle\" problem).",
      "## Strategies for Token-Efficient Context",
      "**1. Summarize, don't dump**: Instead of including a 500-line file, summarize its purpose and key exports.\n**2. Use type signatures**: Include TypeScript interfaces and function signatures instead of full implementations.\n**3. Prioritize boundary files**: Include the files that directly interact with the code being generated.\n**4. Reuse context**: Structure your workflow so that context is built once and refined, not rebuilt from scratch for every prompt.",
      "## How Skyler Optimizes Context",
      "Skyler uses intelligent context assembly to ensure every token counts. It analyzes your project's dependency graph, identifies the most relevant files, and structures the context with the most important information at the beginning and end of the prompt (where model attention is strongest).",
    ],
  },
  {
    slug: "chain-of-thought-prompting",
    title: "The Art of Chain-of-Thought Prompting",
    description:
      "Chain-of-thought prompting is one of the most powerful techniques for complex AI reasoning. Learn when and how to use it for debugging, architecture design, and code reviews.",
    category: "Prompt Engineering",
    readTime: "7 min read",
    date: "Mar 25, 2026",
    author: "Skyler Team",
    authorRole: "Developer Advocacy",
    coverGradient: "from-fuchsia-600 to-purple-600",
    content: [
      "## What Is Chain-of-Thought Prompting?",
      "Chain-of-thought (CoT) prompting is a technique where you ask the AI to think through a problem step by step before providing a final answer. Instead of jumping to a conclusion, the model works through the reasoning process explicitly.",
      "## Why It Works",
      "Language models are autoregressive — they generate one token at a time, where each token is influenced by all previous tokens. When you ask a model to show its reasoning, each reasoning step becomes part of the context for subsequent steps. This creates a self-reinforcing chain of logic that leads to more accurate conclusions.",
      "## When to Use CoT",
      "Chain-of-thought is most valuable for:\n- **Debugging**: *\"Walk through this function step by step. Track the value of each variable at each line. Where does the bug occur?\"*\n- **Architecture decisions**: *\"Consider the tradeoffs between microservices and a monolith for this use case. Think through scalability, developer experience, and operational complexity.\"*\n- **Code reviews**: *\"Review this pull request. For each change, explain what it does, why it might be needed, and any potential issues.\"*\n- **Algorithm design**: *\"Design a function that finds the shortest path in a weighted graph. Think about edge cases, time complexity, and space complexity at each step.\"*",
      "## CoT Patterns for Developers",
      "### The Debugger Pattern",
      "```\nThis function returns unexpected results. Please:\n1. Read the function line by line\n2. For each line, state what it does and what value each variable holds\n3. Identify where the actual behavior diverges from expected behavior\n4. Suggest a fix with explanation\n```",
      "### The Architect Pattern",
      "```\nI need to design [feature]. Before writing any code:\n1. List the components this feature will need\n2. Describe how they interact\n3. Identify potential edge cases\n4. Propose the implementation approach\n5. Only then, write the code\n```",
      "### The Reviewer Pattern",
      "```\nReview this code and for each section:\n1. Summarize what it does\n2. Rate it (good/ok/needs improvement)\n3. If needs improvement, explain why and suggest an alternative\n```",
      "## Combining CoT with Other Techniques",
      "CoT is most powerful when combined with role-based prompting (*\"You are a senior engineer...\"*) and context engineering (providing the right codebase context). This triad — role, context, and reasoning — produces consistently expert-level outputs.",
    ],
  },
  {
    slug: "building-ai-agents",
    title: "Building Autonomous AI Agents: A Practical Guide",
    description:
      "AI agents are the next frontier. Learn the core patterns — tool use, planning loops, memory systems — and how to build agents that can autonomously complete complex coding tasks.",
    category: "AI Agents",
    readTime: "15 min read",
    date: "Mar 22, 2026",
    author: "Skyler Team",
    authorRole: "Engineering",
    coverGradient: "from-sky-500 to-blue-700",
    content: [
      "## The Age of AI Agents",
      "We're entering a new era where AI systems don't just respond to prompts — they take autonomous action. AI agents can plan, execute, observe, and iterate on tasks with minimal human intervention. For developers, this means AI that can build entire features, not just write individual functions.",
      "## What Makes an Agent Different from a Chatbot?",
      "A chatbot generates a single response to a prompt. An agent operates in a feedback loop:\n1. **Plan**: Break down a goal into steps.\n2. **Act**: Execute a step using available tools.\n3. **Observe**: Check the result.\n4. **Reflect**: Decide what to do next based on the outcome.\n5. **Repeat**: Continue until the goal is achieved.",
      "## Core Agent Patterns",
      "### Tool Use",
      "Agents need tools to interact with the world. In a coding context, tools might include:\n- File system operations (read, write, create, delete)\n- Terminal commands (npm install, git commit)\n- Browser interactions (testing UIs)\n- API calls (fetching docs, creating resources)\n- Code analysis (linting, type-checking, test running)",
      "### Planning & Decomposition",
      "Before acting, effective agents decompose complex tasks into manageable steps. A good planning prompt might produce:\n```\nGoal: Add user authentication to the dashboard\nPlan:\n1. Install Supabase auth dependencies\n2. Create auth configuration file\n3. Build login page component\n4. Add auth middleware\n5. Protect dashboard routes\n6. Add logout functionality\n7. Test all auth flows\n```",
      "### Memory Systems",
      "Agents need memory to maintain context across long tasks. There are three types:\n- **Short-term memory**: The current context window. Contains the active conversation and recent actions.\n- **Working memory**: A scratchpad for the current task — notes, intermediate results, decisions made.\n- **Long-term memory**: Persistent knowledge about the project, team preferences, and past decisions.",
      "### Error Recovery",
      "Real-world tasks inevitably encounter errors. Robust agents need strategies for:\n- Syntax errors in generated code (re-generate with error context)\n- Failed tests (analyze failure, hypothesize fix, retry)\n- Missing dependencies (install and retry)\n- Ambiguous requirements (ask for clarification or make a reasonable assumption and note it)",
      "## Building Your First Agent",
      "You don't need a complex framework to build an agent. The core loop is simple:",
      "```typescript\nasync function agentLoop(goal: string) {\n  const plan = await llm.plan(goal)\n  for (const step of plan.steps) {\n    const result = await execute(step)\n    if (result.error) {\n      const recovery = await llm.recover(step, result.error)\n      await execute(recovery)\n    }\n  }\n}\n```",
      "## The Future of Coding Agents",
      "We're moving toward a world where developers describe *what* they want, and agents handle the *how*. This doesn't replace developers — it amplifies them. The developers who learn to effectively direct agents will be orders of magnitude more productive than those who don't.",
    ],
  },
  {
    slug: "rag-vs-fine-tuning",
    title: "RAG vs Fine-Tuning: Choosing the Right Approach",
    description:
      "Should you use Retrieval-Augmented Generation or fine-tune a model? Understand the tradeoffs, costs, and practical considerations for each approach in coding applications.",
    category: "AI Architecture",
    readTime: "11 min read",
    date: "Mar 19, 2026",
    author: "Skyler Team",
    authorRole: "AI Research",
    coverGradient: "from-lime-500 to-green-600",
    content: [
      "## Two Paths to Customization",
      "When you want an AI model to work with your specific domain knowledge — your codebase, your documentation, your conventions — you have two main approaches: Retrieval-Augmented Generation (RAG) and fine-tuning. Each has distinct strengths and tradeoffs.",
      "## What Is RAG?",
      "RAG combines a retrieval system with a generation model. When a user asks a question:\n1. The system searches a knowledge base (your codebase, docs, etc.) for relevant information.\n2. The retrieved documents are injected into the prompt as context.\n3. The model generates an answer grounded in the retrieved information.",
      "**Pros**: No model training needed. Knowledge can be updated instantly. Works with any base model. Transparent (you can see what was retrieved).\n**Cons**: Limited by context window size. Retrieval quality directly affects output quality. Higher latency due to the retrieval step.",
      "## What Is Fine-Tuning?",
      "Fine-tuning involves training a base model on your specific data to permanently adjust its weights. The model learns your patterns, conventions, and domain knowledge at a fundamental level.",
      "**Pros**: Faster inference (no retrieval step). Deep understanding of patterns. Better for style/format consistency. Works when context windows are too small.\n**Cons**: Expensive to train and maintain. Knowledge becomes stale without retraining. Requires curated training data. Risk of catastrophic forgetting.",
      "## Decision Framework",
      "Use this framework to choose:\n\n| Factor | Use RAG | Use Fine-Tuning |\n|--------|---------|------------------|\n| Knowledge changes frequently | ✅ | ❌ |\n| Need transparent sourcing | ✅ | ❌ |\n| Domain is very specialized | ❌ | ✅ |\n| Budget is limited | ✅ | ❌ |\n| Latency is critical | ❌ | ✅ |\n| Style consistency matters | ❌ | ✅ |",
      "## The Hybrid Approach",
      "In practice, the best systems use both. Fine-tune a model for your domain's general patterns and coding style, then use RAG to inject specific, up-to-date information at query time. This gives you the consistency of fine-tuning with the currency of RAG.",
      "## RAG for Codebases",
      "Building a RAG system for code requires special considerations:\n- **Chunking strategy**: Code should be chunked by logical units (functions, classes, modules) not by arbitrary character counts.\n- **Embedding model**: Use code-specific embedding models (like CodeBERT or StarEncoder) rather than general-purpose text embeddings.\n- **Metadata enrichment**: Include file paths, import statements, and type information in your chunks.\n- **Hybrid search**: Combine semantic search with keyword search — exact function and variable names matter in code.",
      "## How Skyler Uses RAG Principles",
      "Skyler doesn't implement RAG in the traditional sense (it doesn't maintain a vector database), but it applies RAG principles by intelligently retrieving relevant files from your project structure and assembling them into context-rich prompts. It's RAG without the infrastructure overhead.",
      "## Making Your Choice",
      "For most developer tools and coding assistants, RAG is the right starting point. It's simpler to implement, cheaper to operate, and more flexible. Save fine-tuning for when you have a specific, well-defined need that RAG can't meet — like matching a very specific code style or generating domain-specific patterns that require deep understanding.",
    ],
  },
]

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return blogArticles.find((article) => article.slug === slug)
}

export function getArticlesByCategory(category: string): BlogArticle[] {
  if (category === "All") return blogArticles
  return blogArticles.filter((article) => article.category === category)
}
